(()=>{
const $=s=>document.querySelector(s),screen=$('[data-screen="login"]'),pad=$('#patternPad'),canvas=$('#patternWater'),ctx=canvas.getContext('2d'),status=$('#patternStatus'),buttons=[...pad.querySelectorAll('.pattern-dot')],reduced=matchMedia('(prefers-reduced-motion: reduce)');
let selected=[],drawing=false,pointer=null,tip=null,ripples=[],raf=0,done=false,releaseTimer=0,trail=[],lastTrail=null;
const dropSprite=new Image();dropSprite.src='assets/real-water-drop.png';dropSprite.onload=()=>paint(performance.now());
const points=buttons.map((b,i)=>({x:54+(i%3)*96,y:54+Math.floor(i/3)*96}));
function say(s){status.textContent=s}function reset(){clearTimeout(releaseTimer);selected=[];done=false;tip=null;ripples=[];trail=[];lastTrail=null;buttons.forEach(b=>b.classList.remove('chosen'));say('4개 이상의 점을 이어보세요.');paint(performance.now());}
function add(i){if(selected.includes(i))return;const prev=selected.at(-1);if(prev!==undefined){const a=points[prev],b=points[i];const middle=points.findIndex(p=>p.x===(a.x+b.x)/2&&p.y===(a.y+b.y)/2);if(middle>=0&&middle!==prev&&!selected.includes(middle)){selected.push(middle);buttons[middle].classList.add('chosen')}}selected.push(i);buttons[i].classList.add('chosen');ripples.push({...points[i],time:performance.now()});}
function local(e){const r=pad.getBoundingClientRect();return{x:(e.clientX-r.left)*300/r.width,y:(e.clientY-r.top)*300/r.height}}
function hit(p){points.forEach((q,i)=>{if(Math.hypot(p.x-q.x,p.y-q.y)<27)add(i)})}
function track(p){if(!reduced.matches){const now=performance.now(),from=lastTrail||p,n=Math.min(50,Math.max(1,Math.ceil(Math.hypot(p.x-from.x,p.y-from.y)/5)));for(let i=1;i<=n;i++)trail.push({x:from.x+(p.x-from.x)*i/n,y:from.y+(p.y-from.y)*i/n,time:now,radius:3+Math.random()*3.5,seed:Math.random()*6.28});trail=trail.slice(-180);lastTrail={...p};}if(tip){const n=Math.max(1,Math.ceil(Math.hypot(p.x-tip.x,p.y-tip.y)/8));for(let i=1;i<=n;i++)hit({x:tip.x+(p.x-tip.x)*i/n,y:tip.y+(p.y-tip.y)*i/n})}else hit(p);tip=p;}
function stroke(color,width){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();selected.forEach((i,n)=>n?ctx.lineTo(points[i].x,points[i].y):ctx.moveTo(points[i].x,points[i].y));if(drawing&&tip&&selected.length)ctx.lineTo(tip.x,tip.y);ctx.stroke()}
function bead(x,y,r,alpha,t){if(dropSprite.complete&&dropSprite.naturalWidth){ctx.save();ctx.globalAlpha=alpha*.82;ctx.translate(x,y);ctx.rotate(Math.sin(t*.8)*.10);ctx.drawImage(dropSprite,-r*1.18,-r*1.18,r*2.36,r*2.36);ctx.restore();return;}
ctx.save();ctx.translate(x,y);ctx.globalAlpha=alpha;ctx.rotate(Math.sin(t*.8)*.18);
const g=ctx.createRadialGradient(-r*.3,-r*.4,r*.06,0,0,r);g.addColorStop(0,'rgba(255,255,255,.98)');g.addColorStop(.25,'rgba(236,255,250,.4)');g.addColorStop(.62,'rgba(180,222,211,.2)');g.addColorStop(.84,'rgba(73,146,130,.5)');g.addColorStop(.95,'rgba(242,233,192,.85)');g.addColorStop(1,'rgba(57,111,101,.4)');ctx.fillStyle=g;
ctx.beginPath();for(let j=0;j<=40;j++){const a=j/40*Math.PI*2,rr=r*(1+.065*Math.sin(a*3+t));const px=Math.cos(a)*rr,py=Math.sin(a)*rr*.9;j?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(74,132,115,.35)';ctx.lineWidth=.6;ctx.stroke();ctx.beginPath();ctx.ellipse(-r*.28,-r*.38,r*.3,r*.12,-.5,0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,.94)';ctx.fill();ctx.restore();
}
function paint(now){ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,300,300);stroke('rgba(76,139,121,.15)',2.2);
trail=trail.filter(p=>now-p.time<1100);
for(const p of trail){const age=(now-p.time)/1100,a=(1-age)**2;const yy=p.y+age*7;
const halo=ctx.createRadialGradient(p.x,yy,0,p.x,yy,24+age*14);halo.addColorStop(0,`rgba(139,204,185,${a*.23})`);halo.addColorStop(.4,`rgba(222,216,169,${a*.1})`);halo.addColorStop(1,'rgba(210,241,225,0)');ctx.fillStyle=halo;ctx.fillRect(p.x-40,yy-40,80,80);
bead(p.x+Math.sin(p.seed+age*3)*age*3,yy,p.radius*(1-age*.7),a*.75,now*.002+p.seed);
ctx.beginPath();ctx.arc(p.x+Math.sin(p.seed)*9,yy+Math.cos(p.seed)*9,1.2*(1-age),0,Math.PI*2);ctx.fillStyle=`rgba(255,255,255,${a})`;ctx.fill();}
for(const i of selected){const p=points[i];bead(p.x,p.y,10.5,1,reduced.matches?0:now*.002+i);const age=(now-(ripples.find(r=>r.x===p.x&&r.y===p.y)?.time||now))/1000;if(age<.9&&!reduced.matches){ctx.strokeStyle=`rgba(78,149,128,${(.9-age)*.28})`;ctx.lineWidth=.7;ctx.beginPath();ctx.ellipse(p.x,p.y,12+age*17,10+age*14,0,0,Math.PI*2);ctx.stroke()}}
if(drawing&&tip){const g=ctx.createRadialGradient(tip.x,tip.y,1,tip.x,tip.y,31);g.addColorStop(0,'rgba(214,249,234,.5)');g.addColorStop(1,'rgba(214,249,234,0)');ctx.fillStyle=g;ctx.fillRect(tip.x-32,tip.y-32,64,64);bead(tip.x,tip.y,13,1,reduced.matches?0:now*.002)}
}
function animate(now){paint(now);if(screen.classList.contains('active')&&!document.hidden&&(drawing||selected.length||trail.length)&&!reduced.matches)raf=requestAnimationFrame(animate)}function start(){cancelAnimationFrame(raf);raf=requestAnimationFrame(animate)}
pad.addEventListener('pointerdown',e=>{if(e.button!==0)return;reset();drawing=true;pointer=e.pointerId;pad.setPointerCapture(pointer);track(local(e));start();});pad.addEventListener('pointermove',e=>{if(!drawing||e.pointerId!==pointer)return;track(local(e));if(reduced.matches)paint(performance.now())});
function finish(cancel=false){drawing=false;pointer=null;tip=null;if(cancel){reset();return}done=selected.length>=4;say(done?'패턴을 이었어요. 체험 화면으로 들어갈 수 있어요.':'4개 이상의 점을 연결해주세요.');paint(performance.now());releaseTimer=setTimeout(reset,3500)}
pad.addEventListener('pointerup',()=>finish());pad.addEventListener('pointercancel',()=>finish(true));buttons.forEach((b,i)=>b.addEventListener('click',e=>{if(e.detail===0){if(done)reset();add(i);done=selected.length>=4;say(done?'패턴 준비 완료 · 체험 화면으로 들어가세요.':selected.length+'개 선택 · 4개 이상 이어주세요.');start()}}));$('#patternReset').onclick=reset;
const tabs=[...document.querySelectorAll('[data-login-method]')];function method(name){tabs.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.loginMethod===name)));$('#patternPanel').hidden=name!=='pattern';$('.password-field').hidden=name==='pattern';$('#loginSubmitText').textContent=name==='pattern'?'패턴으로 체험하기':'집사 만나기';reset()};tabs.forEach(b=>b.onclick=()=>method(b.dataset.loginMethod));method('pattern');
$('.login-form').onsubmit=e=>{e.preventDefault();if(!$('#patternPanel').hidden&&!done){say('먼저 4개 이상의 점을 이어주세요.');return}reset();go('home')};
// Condensation is decorative and dismissible; never a security boundary.
const fog=$('#loginFog'),clear=$('#clearFog');let idle=0,fogging=false,wiping=false,lastWipe=null,holes=[],fw=0,fh=0;
const moisture=document.createElement('canvas');moisture.setAttribute('aria-hidden','true');Object.assign(moisture.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none',zIndex:'27'});screen.append(moisture);const mc=moisture.getContext('2d');let beads=[],rimFrame=0,lastWet=null;
function sizeMoisture(){const d=Math.min(devicePixelRatio||1,2);moisture.width=Math.ceil(fw*d);moisture.height=Math.ceil(fh*d);mc.setTransform(d,0,0,d,0,0);beads=[];lastWet=null;}
function pushMoisture(p){if(reduced.matches)return;const now=performance.now();const old=lastWet||{x:p.x,y:p.y-1},dx=p.x-old.x,dy=p.y-old.y,dist=Math.hypot(dx,dy);if(lastWet&&dist<5)return;const angle=Math.atan2(dy,dx),steps=Math.min(12,Math.max(1,Math.ceil(dist/10)));for(let j=1;j<=steps;j++){const x=old.x+dx*j/steps,y=old.y+dy*j/steps;beads.push({x,y,angle,time:now,kind:'rim'});for(const side of [-1,1]){const a=angle+side*Math.PI/2,offset=34+Math.random()*5;beads.push({x:x+Math.cos(a)*offset,y:y+Math.sin(a)*offset,r:1.1+Math.random()*1.9,time:now,kind:'drop'})}}beads=beads.slice(-240);lastWet=p;if(!rimFrame)rimFrame=requestAnimationFrame(drawMoisture);}
function drawMoisture(now){rimFrame=0;mc.clearRect(0,0,fw,fh);beads=beads.filter(b=>now-b.time<850);for(const b of beads){const age=(now-b.time)/850,alpha=(1-age)**2*(wiping?1:.7);mc.save();mc.globalAlpha=alpha;if(b.kind==='rim'){mc.lineCap='round';mc.beginPath();mc.ellipse(b.x,b.y+age*2,36,34,0,b.angle-.8,b.angle+.8);mc.strokeStyle='rgba(81,119,109,.16)';mc.lineWidth=2.2;mc.stroke();mc.beginPath();mc.ellipse(b.x-.4,b.y-.7+age*2,35,33,0,b.angle-.8,b.angle+.8);mc.strokeStyle='rgba(255,255,255,.62)';mc.lineWidth=.9;mc.stroke()}else{const y=b.y+age*age*8,r=b.r*(1-age*.3);const g=mc.createRadialGradient(b.x-r*.3,y-r*.4,.1,b.x,y,r);g.addColorStop(0,'rgba(255,255,255,.85)');g.addColorStop(.42,'rgba(226,245,236,.18)');g.addColorStop(.82,'rgba(145,182,169,.23)');g.addColorStop(1,'rgba(74,109,98,.3)');mc.fillStyle=g;mc.beginPath();mc.ellipse(b.x,y,r,r*(1+age*.35),0,0,Math.PI*2);mc.fill()}mc.restore()}if(beads.length&&!document.hidden&&screen.classList.contains('active'))rimFrame=requestAnimationFrame(drawMoisture);else mc.clearRect(0,0,fw,fh);}

const rainFX=window.CrownyRain?new CrownyRain(screen):null;
const dew=document.createElement('canvas');dew.setAttribute('aria-hidden','true');dew.dataset.rainOverlay='true';moisture.dataset.rainOverlay='true';Object.assign(dew.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none',zIndex:'28'});screen.append(dew);const dc=dew.getContext('2d');
const mask=document.createElement('canvas'),maskCtx=mask.getContext('2d');let drops=[],dropFrame=0,dropLast=0,fogStart=0,maskDirty=false,lastMask=0,tapDrop=false,tiltX=0,tiltY=0,baseBeta=null,baseGamma=null,sensorStarted=false;
function applyFogMask(){fog.style.maskImage=fog.style.webkitMaskImage=`url(${mask.toDataURL()})`;maskDirty=false;}
function cutPath(a,b,r){maskCtx.save();maskCtx.globalCompositeOperation='destination-out';maskCtx.lineCap='round';for(const [width,alpha]of [[r*2+.8,.15],[r*1.8,.35],[r*1.5,1]]){maskCtx.strokeStyle=`rgba(0,0,0,${alpha})`;maskCtx.lineWidth=width;maskCtx.beginPath();maskCtx.moveTo(a.x,a.y);maskCtx.lineTo(b.x,b.y);maskCtx.stroke()}maskCtx.restore();maskDirty=true;}
// Independent condensation, pinning and irregular gravity-driven travel.
let nextSlip=0,nextCondense=0;
function makeDrop(x,y,now,delay=0){return{x,y,anchorX:x,anchorY:y,vx:0,vy:0,r:5+Math.random()*5,falling:false,delay,born:now,phase:Math.random()*30,shape:Math.floor(Math.random()*4),shapeTilt:(Math.random()-.5)*.3,visualR:0,speed:11+Math.random()*16,drift:0,turnAt:0};}
function startSlide(b,now,touched=false){b.falling=true;b.initialR=b.r;b.vy=touched?18:2;b.speed=touched?70+Math.random()*35:11+Math.random()*16;b.turnAt=now;b.vx=tiltX*5;}
function weatherDrops(now){if(reduced.matches||wiping)return;
 if(now>=nextSlip){const resting=drops.filter(b=>!b.falling&&!b.absorbed&&now-b.born>2000);if(drops.filter(b=>b.falling&&!b.absorbed).length<4&&resting.length)startSlide(resting[Math.floor(Math.random()*resting.length)],now);nextSlip=now+1800+Math.random()*2400;}
 if(now>=nextCondense){nextCondense=now+1100+Math.random()*1700;if(drops.filter(b=>!b.absorbed).length<14){const rect=fog.getBoundingClientRect(),top=Math.max(30,-rect.top+55),bottom=Math.min(fh-35,innerHeight-rect.top-145);for(let i=0;i<16;i++){const x=25+Math.random()*Math.max(1,fw-50),y=top+Math.random()*Math.max(1,bottom-top);if(y>=fh||drops.some(b=>!b.absorbed&&Math.hypot(b.x-x,b.y-y)<35))continue;if(maskCtx.getImageData(Math.floor(x),Math.floor(y),1,1).data[3]<100)continue;drops.push(makeDrop(x,y,now));break;}}}
}
function initDrops(){rainFX?.resize(fw,fh);const d=Math.min(devicePixelRatio||1,2);dew.width=Math.ceil(fw*d);dew.height=Math.ceil(fh*d);dc.setTransform(d,0,0,d,0,0);mask.width=Math.ceil(fw);mask.height=Math.ceil(fh);maskCtx.fillStyle='white';maskCtx.fillRect(0,0,fw,fh);fog.style.maskImage=fog.style.webkitMaskImage='';
 const rect=fog.getBoundingClientRect(),top=Math.max(30,-rect.top+55),bottom=Math.min(fh-50,innerHeight-rect.top-160);drops=Array.from({length:14},(_,i)=>{const x=30+(fw-60)*((i%4+.25+Math.random()*.5)/4),y=top+Math.max(80,bottom-top)*(Math.floor(i/4)+.3+Math.random()*.35)/4;return makeDrop(x,y,performance.now(),i*.06)});fogStart=performance.now();nextSlip=fogStart+2400+Math.random()*600;nextCondense=fogStart+4000;dropLast=0;cancelAnimationFrame(dropFrame);dropFrame=requestAnimationFrame(drawDrops);}
function drawDrops(now){dropFrame=0;if(!fogging||document.hidden||!screen.classList.contains('active'))return;const dt=Math.min((now-dropLast)/1000||.016,.04);dropLast=now;dc.clearRect(0,0,fw,fh);weatherDrops(now);
 for(const b of drops){if(b.absorbed)continue;const prev={x:b.x,y:b.y};if(b.falling){if(now>=b.turnAt){b.drift=(Math.random()-.5)*16;b.turnAt=now+650+Math.random()*1900;}
 const t=now/1000,grip=.35+.65*(.5+.5*Math.sin(t*1.13+b.phase))**2,targetY=b.speed*grip*Math.min(2,b.r/b.initialR);
 b.vy+=(targetY-b.vy)*Math.min(1,dt*1.7);const targetX=b.drift+Math.sin(t*.83+b.phase)*5+Math.sin(t*2.07+b.phase*.7)*2+tiltX*12;
 b.vx+=(targetX-b.vx)*Math.min(1,dt*1.3);b.x=Math.max(b.r+2,Math.min(fw-b.r-2,b.x+b.vx*dt));b.y+=Math.max(.8,b.vy)*dt;
 const distance=Math.hypot(b.x-prev.x,b.y-prev.y);b.initialR??=b.r;
 if(b.y>=0&&b.y<fh&&b.x>=0&&b.x<fw){const wet=maskCtx.getImageData(Math.floor(b.x),Math.floor(b.y),1,1).data[3]/255;const grown=Math.sqrt(b.r*b.r+distance*b.r*.012*wet);b.r=Math.max(b.r,Math.min(b.initialR*1.65,grown));}
 for(const other of drops){if(other===b||other.absorbed||other.y>fh||Math.hypot(other.x-b.x,other.y-b.y)>b.r+other.r*.65)continue;const area=b.r*b.r,added=other.r*other.r;b.r=Math.min(28,Math.sqrt(area+added));b.vx=(b.vx*area+other.vx*added)/(area+added);other.absorbed=true;other.y=fh+100;}
 cutPath(prev,b,b.r*.8);}else if(!reduced.matches){const tx=b.anchorX+tiltX*9,ty=b.anchorY+tiltY*5;b.vx+=((tx-b.x)*24-b.vx*6)*dt;b.vy+=((ty-b.y)*24-b.vy*6)*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;}
 const opacity=reduced.matches?1:Math.min(.86,Math.max(0,(now-b.born)/1800-b.delay));if(b.y>fh+20)continue;dc.save();dc.translate(b.x,b.y);dc.globalAlpha=opacity;const wobble=reduced.matches?0:Math.sin(now*.003+b.phase)*.05+tiltX*.06,stretch=b.falling?1+Math.min(.8,.18+b.vy/180+Math.max(0,b.r/(b.initialR||b.r)-1)*.28):1+wobble;dc.rotate(b.falling?-Math.atan2(b.vx,Math.max(15,b.vy))*.28:-tiltX*.14);const morph=b.falling?Math.min(1,b.vy/55):0,profiles=[[1,1],[.83,1.2],[1.22,.83],[.94,1.08]],profile=profiles[b.shape];
 dc.rotate(b.shapeTilt*(1-morph));dc.scale((profile[0]+(1-profile[0])*morph)/Math.sqrt(stretch),(profile[1]+(1-profile[1])*morph)*stretch);
 b.visualR=b.visualR?b.visualR+(b.r-b.visualR)*Math.min(1,dt*5):b.r;
 if(dropSprite.complete&&dropSprite.naturalWidth){dc.globalAlpha*=.9;if(b.falling||b.shape===3){const size=b.visualR*2.36,amount=b.falling?Math.min(1,.35+b.vy/130):.22;for(let row=0;row<40;row++){const u=row/40,width=size*(1-amount*.23*(1-u)**2);dc.drawImage(dropSprite,0,u*dropSprite.height,dropSprite.width,dropSprite.height/40, -width/2+(b.shape===3?Math.sin(u*Math.PI*1.5)*size*.065*(1-morph):0),-size/2+u*size,width,size/40+.12)}}else dc.drawImage(dropSprite,-b.visualR*1.18,-b.visualR*1.18,b.visualR*2.36,b.visualR*2.36);dc.restore();continue;}const r=b.r,g=dc.createRadialGradient(-r*.32,-r*.38,.4,0,0,r);g.addColorStop(0,'rgba(255,255,255,.95)');g.addColorStop(.2,'rgba(241,255,250,.5)');g.addColorStop(.55,'rgba(192,219,209,.13)');g.addColorStop(.85,'rgba(83,136,117,.4)');g.addColorStop(1,'rgba(237,234,205,.75)');dc.fillStyle=g;dc.beginPath();dc.ellipse(0,0,r,r*.96,0,0,Math.PI*2);dc.fill();dc.strokeStyle='rgba(74,111,98,.25)';dc.lineWidth=.6;dc.stroke();dc.beginPath();dc.ellipse(-r*.25,-r*.35,r*.28,r*.13,-.5,0,Math.PI*2);dc.fillStyle='rgba(255,255,255,.9)';dc.fill();dc.restore();}
 if(rainFX?.ready){if(!rainFX.engine)rainFX.resize(fw,fh);if(rainFX.render(drops,now))dc.clearRect(0,0,fw,fh);}
 drops=drops.filter(b=>b.y<fh+30);if(maskDirty&&now-lastMask>65){applyFogMask();lastMask=now}if(!reduced.matches||drops.some(b=>b.falling))dropFrame=requestAnimationFrame(drawDrops);}
function releaseDrop(e){const rect=fog.getBoundingClientRect(),p={x:e.clientX-rect.left,y:e.clientY-rect.top};const candidates=drops.filter(b=>!b.falling&&Math.hypot(b.x-p.x,b.y-p.y)<Math.max(22,b.r*2));candidates.sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y));const b=candidates[0];if(!b)return false;startSlide(b,performance.now(),true);if(reduced.matches){cutPath(b,{x:b.x,y:fh},b.r*.8);b.y=fh+40;applyFogMask()}if(!dropFrame)dropFrame=requestAnimationFrame(drawDrops);return true;}
const fogCharacter=screen.querySelector('.crowny-character'),fogSpeech=screen.querySelector('.speech');let beforeFogState=null,beforeFogSpeech=null;
function restoreFogCharacter(){screen.classList.remove('fog-character-active');if(beforeFogState!==null){fogCharacter?._crowny?.setState(beforeFogState);beforeFogState=null;}if(beforeFogSpeech!==null){fogSpeech.textContent=beforeFogSpeech;beforeFogSpeech=null;}}
function clearFog(){rainFX?.clear();restoreFogCharacter();lastWet=null;fogging=wiping=tapDrop=false;holes=[];lastWipe=null;drops=[];cancelAnimationFrame(dropFrame);dropFrame=0;dc.clearRect(0,0,fw,fh);fog.classList.remove('fog-visible');fog.style.maskImage='';fog.style.webkitMaskImage='';clear.hidden=true;armIdle()}
let weatherMode='rain';
function armIdle(){clearTimeout(idle);if(weatherMode==='off'||weatherMode==='clear')return;if(!screen.classList.contains('active')||document.hidden||reduced.matches||document.activeElement?.matches('input,textarea'))return;idle=setTimeout(showFog,5000)}
function showFog(){if(weatherMode==='off'||weatherMode==='clear')return;if(!screen.classList.contains('active')||document.hidden||drawing)return;const r=screen.getBoundingClientRect();fw=r.width;fh=r.height;sizeMoisture();if(!fogging){beforeFogState=fogCharacter?._crowny?.baseState||'greet';beforeFogSpeech=fogSpeech?.textContent||'';}fogging=true;screen.classList.add('fog-character-active');fogCharacter?._crowny?.setState('curious');if(fogSpeech)fogSpeech.textContent='잠깐 쉬고 계신가요?';fog.classList.add('fog-visible');clear.hidden=false;clear.textContent='물방울을 누르거나, 문질러 닦아보세요 · 전체 지우기';initDrops();}
function wipe(e){const r=fog.getBoundingClientRect(),p={x:e.clientX-r.left,y:e.clientY-r.top};const from=lastWipe||p,steps=Math.max(1,Math.ceil(Math.hypot(p.x-from.x,p.y-from.y)/8));for(let j=0;j<=steps;j++){const clientX=r.left+from.x+(p.x-from.x)*j/steps,clientY=r.top+from.y+(p.y-from.y)*j/steps;for(let k=0;k<drops.length;k++){if(!releaseDrop({clientX,clientY}))break}}cutPath(lastWipe||{x:p.x-.1,y:p.y},p,36);pushMoisture(p);rainFX?.wipe(p.x,p.y,36);lastWipe=p;applyFogMask();}
fog.addEventListener('pointerdown',e=>{fog.setPointerCapture(e.pointerId);tapDrop=releaseDrop(e);if(tapDrop)return;wiping=true;wipe(e)});fog.addEventListener('pointermove',e=>{if(tapDrop){tapDrop=false;wiping=true;}if(wiping)wipe(e)});fog.addEventListener('pointerup',()=>{if(tapDrop){tapDrop=false;return}clearFog()});fog.addEventListener('pointercancel',()=>{if(wiping)clearFog();tapDrop=false});clear.onclick=clearFog;$('#tryFog').onclick=()=>{weatherMode='mist';weatherSelect.value='mist';screen.dataset.weather='mist';clearTimeout(idle);showFog()};
const tiltButton=document.createElement('button');tiltButton.type='button';tiltButton.textContent='기울기 효과 켜기';tiltButton.id='enableTilt';$('.pattern-tools').append(tiltButton);
function orientation(e){if(!screen.classList.contains('active')||document.hidden||reduced.matches||e.beta===null||e.gamma===null)return;if(baseBeta===null){baseBeta=e.beta;baseGamma=e.gamma}tiltX=Math.max(-1,Math.min(1,(e.gamma-baseGamma)/22));tiltY=Math.max(-1,Math.min(1,(e.beta-baseBeta)/22));tiltButton.textContent='기울기 연결됨';}
tiltButton.onclick=async()=>{if(sensorStarted){baseBeta=baseGamma=null;return}if(!window.isSecureContext){tiltButton.textContent='HTTPS 주소에서 사용 가능';return}if(!window.DeviceOrientationEvent){tiltButton.textContent='기울기 미지원 · 터치는 가능';return}try{if(typeof DeviceOrientationEvent.requestPermission==='function'){const result=await DeviceOrientationEvent.requestPermission();if(result!=='granted'){tiltButton.textContent='허용되지 않음 · 터치는 가능';return}}sensorStarted=true;addEventListener('deviceorientation',orientation,{passive:true});tiltButton.textContent='휴대폰을 살짝 기울여보세요';setTimeout(()=>{if(baseBeta===null)tiltButton.textContent='센서 응답 없음 · 터치는 가능'},6000)}catch{tiltButton.textContent='연결 불가 · 터치는 가능'}};
const weatherControl=document.createElement('label');weatherControl.className='weather-preview';weatherControl.innerHTML='배경 체험 <select aria-label="배경 날씨 체험"><option value="rain">비 · 물방울</option><option value="mist">김 서림</option><option value="clear">맑음</option><option value="off">효과 끄기</option></select><small>실제 날씨 미연동</small>';screen.querySelector('.login-intro').before(weatherControl);const weatherSelect=weatherControl.querySelector('select');screen.dataset.weather='rain';
function setWeather(mode){if(!['rain','mist','clear','off'].includes(mode))return;weatherMode=mode;weatherSelect.value=mode;screen.dataset.weather=mode;clearFog();if(mode==='rain'||mode==='mist'){clearTimeout(idle);showFog();}}
weatherSelect.addEventListener('change',()=>setWeather(weatherSelect.value));
// Provider-independent integration point; no location or weather service is called.
window.CrownyWeather={set: setWeather,get mode(){return weatherMode}};
['pointerdown','pointermove','keydown','wheel','input','focusin','focusout'].forEach(type=>screen.addEventListener(type,()=>{if(!fogging)armIdle()},{passive:true}));document.addEventListener('keydown',e=>{if(fogging){clearFog();if(e.key==='Escape')e.preventDefault()}});document.addEventListener('visibilitychange',()=>{clearTimeout(idle);cancelAnimationFrame(raf);cancelAnimationFrame(dropFrame);if(!document.hidden){clearFog();start()}});let wasLoginActive=screen.classList.contains('active');new MutationObserver(()=>{const active=screen.classList.contains('active');if(active===wasLoginActive)return;wasLoginActive=active;clearTimeout(idle);cancelAnimationFrame(raf);reset();clearFog()}).observe(screen,{attributes:true,attributeFilter:['class']});reduced.addEventListener('change',clearFog);addEventListener('resize',()=>{if(fogging)clearFog()});armIdle();

})();